#!/usr/bin/env bash

### Aliases
## System
alias ls='ls --color=always'



### Environment
export QT_QPA_PLATFORMTHEME=qt6ct



### Path
## Local folders
list_path=(
	~/.local/bin
	~/.emacs.d/bin
)

PATH_TMP=${PATH}
for i in ${list_path}
do
	export PATH_TMP="${PATH_TMP}:${i}"
done

export PATH=${PATH_TMP}
