#!/usr/bin/env bash

### Aliases
## System
alias ls='ls --color=always'



### Environment
export QT_QPA_PLATFORMTHEME=qt6ct



### Path
## Local folders
list_path=(
	~/.local/bin
)

for i in ${list_path}
do
	export PATH="${PATH}:${i}"
done
