#!/usr/bin/env zsh

### Sources list
source ~/.antigen.zsh
source ~/.pastefix.zsh
source ~/.powerline.zsh
source ~/.profile
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh



### Plugins
## Syntax
antigen use oh-my-zsh
for i in {zsh-syntax-highlighting,zsh-autosuggestions,zsh-completions,zsh-history-substring-search}
do
	antigen bundle zsh-users/${i}
done

## Theme
#antigen theme denysdovhan/spaceship-prompt
antigen theme romkatv/powerlevel10k

antigen apply



### Configuration
## Powerline prompt
export POWERLINE_COMMAND=powerline
export POWERLINE_CONFIG_COMMAND=powerline-config
#powerline-daemon -q

## Spaceship prompt
#SPACESHIP_CHAR_SYMBOL="λ " # Lambda



### Tmux
# Automatic execution
[ $TERM != "screen" ] && tmux
export TERM=xterm-256color
