# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#!/usr/bin/env zsh

### Sources list
source ~/.antigen.zsh
source ~/.pastefix.zsh
source ~/.powerline.zsh
source ~/.profile
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh



### Plugins
## Syntax
antigen use oh-my-zsh
for i in {zsh-syntax-highlighting,zsh-autosuggestions,zsh-completions,zsh-history-substring-search}
do
	antigen bundle zsh-users/${i}
done

## Theme
#antigen theme denysdovhan/spaceship-prompt
antigen theme romkatv/powerlevel10k

antigen apply



### Configuration
## Powerline prompt
#powerline-daemon -q

## Spaceship prompt
#SPACESHIP_CHAR_SYMBOL="λ " # Lambda

## Tmux
if [ "$TMUX" = "" ]; then tmux; fi
